name: Daily Pipeline

on:
  schedule:
    - cron: '0 17 * * *'  # runs at midnight UTC daily
  workflow_dispatch:       # allows manual trigger

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run pipeline
        env:
          CONN_STRING: ${{ secrets.CONN_STRING }}
        run: python pipeline.py